name: 'OpsLevel - Create Deploy Event'
author: 'OpsLevel <support@opslevel.com>'
description: 'Create a deploy event in OpsLevel'
branding:
  icon: 'package'  
  color: 'blue'
inputs:
  integration_url:
    description: 'The OpsLevel deploy integration url'
    required: true
    default: ''
  service:
    description: 'The service alias for the event'
    required: false
    default: ''
  description:
    description: 'The description or release notes for the event'
    required: false
    default: ''
  environment:
    description: 'The environment for the event'
    required: false
    default: ''
  number:
    description: 'The deploy number for the event'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'

