name: 'OpsLevel - Create Deploy Event'
author: 'OpsLevel <support@opslevel.com>'
description: 'Create a deploy event in OpsLevel'
branding:
  icon: 'package'  
  color: 'blue'
inputs:
  integrationId:
    description: 'The OpsLevel deploy integration id'
    required: true
    default: ''
  service:
    description: 'The service alias for the event'
    required: false
    default: ''
  environment:
    description: 'The environment for the event'
    required: false
    default: ''
  number:
    description: 'The deploy number for the event'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://public.ecr.aws/opslevel/cli:v0.0.1-beta.2'
  args:
    - create
    - deploy
    - -i 
    - ${INPUT_INTEGRATIONID}
    - -s 
    - ${INPUT_SERVICE:-${GITHUB_REPOSITORY}}
    - -e
    - ${INPUT_ENVIRONMENT}
    - -n
    - ${INPUT_NUMBER:-${GITHUB_RUN_NUMBER})
    - -url
    - ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
    - -id
    - ${GITHUB_RUN_ID}
