name: 'OpsLevel - Report Deploy'
author: 'OpsLevel <support@opslevel.com>'
description: 'Create a deploy event for a service in OpsLevel'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  integration_url:
    description: 'The OpsLevel deploy integration url'
    required: true
  deduplication_id:
    description: 'An identifier that can be used to deduplicate deployments'
    required: false
    default: ${{ github.run_id }}
  deployer_email:
    description: 'The deployer email who created the event'
    required: false
    default: ''
  deployer_name:
    description: 'The deployer name who created the event'
    required: false
    default: ${{ github.actor }}
  deploy_url:
    description: 'The deploy url that OpsLevel points to'
    required: false
    default: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  description:
    description: 'The description or release notes for the event'
    required: false
    default: 'Event Created by ${{ github.workflow }}'
  environment:
    description: 'The environment for the event'
    required: false
    default: production
  number:
    description: 'The deploy number for the event'
    required: false
    default: ${{ github.run_number }}
  service:
    description: 'The service alias for the event'
    required: false
    default: ${{ github.repository }}
runs:
  using: "composite"
  steps:
    - name: Install OpsLevel CLI
      uses: opslevel/actions/setup-cli@v1
    - name: Mask inputs
      shell: bash
      run: |
        set +v
        echo ::add-mask::${{ inputs.integration_url }}
        set -v
    - name: Report Deploy to OpsLevel
      shell: bash
      run: |
        cat <<EOF > data.yaml
        service: "${{ inputs.service }}"
        description: "${{ inputs.description }}"
        environment: "${{ inputs.environment }}"
        deploy-number: "${{ inputs.number }}"
        deploy-url: "${{ inputs.deploy_url}}"
        dedup-id: "${{ inputs.deduplication_id }}"
        deployer:
          name: "${{ inputs.deployer_name }}"
          email: "${{ inputs.deployer_email }}"
        EOF
        opslevel create deploy -i "${{ inputs.integration_url }}" -f .
