name: 'OpsLevel - Report Deploy'
author: 'OpsLevel <support@opslevel.com>'
description: 'Create a deploy event for a service in OpsLevel'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  integration_url:
    description: 'The OpsLevel deploy integration url'
    required: true
  deduplication_id:
    description: 'An identifier that can be used to deduplicate deployments'
    required: false
    default: ${{ github.run_id }}
  deployer_email:
    description: 'The deployer email who created the event'
    required: false
    default: ''
  deployer_name:
    description: 'The deployer name who created the event'
    required: false
    default: ${{ github.actor }}
  description:
    description: 'The description or release notes for the event'
    required: false
    default: 'Event Created by OpsLevel Github Action'
  environment:
    description: 'The environment for the event'
    required: false
    default: production
  number:
    description: 'The deploy number for the event'
    required: false
    default: ${{ github.run_number }}
  service:
    description: 'The service alias for the event'
    required: false
    default: ${{ github.repository }}
  use_docker:
    description: 'Send deploy using docker if "true" - use OpsLevel CLI otherwise'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Do it with Docker
      if: ${{ inputs.use_docker == 'true' }}
      uses: OpsLevel/report-deploy-github-action/with-docker@v1.0.0
      with:
        integration_url: ${{ inputs.integration_url }}
        deduplication_id: ${{ inputs.deduplication_id }}
        deployer_email: ${{ inputs.deployer_email }}
        deployer_name: ${{ inputs.deployer_name }}
        description: ${{ inputs.description }}
        environment: ${{ inputs.environment }}
        number: ${{ inputs.number }}
        service: ${{ inputs.service }}
    - name: Install OpsLevel cli
      if: ${{ inputs.use_docker != 'true' }}
      shell: bash
      run: |
        curl -sLS https://raw.githubusercontent.com/OpsLevel/cli/main/install.sh | sudo sh
    - name: Report Deploy to OpsLevel
      if: ${{ inputs.use_docker != 'true' }}
      shell: bash
      run: |
        echo ::add-mask::$INTEGRATION_URL
        cat <<EOF > data.yaml
        service: "$SERVICE"
        description: "$DESCRIPTION"
        environment: "$ENVIRONMENT"
        deploy-number: "$NUMBER"
        deploy-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        dedup-id: "$DEDUPLICATION_ID"
        deployer:
          name: "$DEPLOYER_NAME"
          email: "$DEPLOYER_EMAIL"
        EOF
        opslevel create deploy -i "$INTEGRATION_URL" -f .
      env:
        DESCRIPTION: ${{ inputs.description }}
        DEPLOYER_EMAIL: ${{ inputs.deployer_email }}
        DEPLOYER_NAME: ${{ inputs.deployer_name }}
        DEDUPLICATION_ID: ${{ inputs.deduplication_id }}
        ENVIRONMENT: ${{ inputs.environment }}
        INTEGRATION_URL: ${{ inputs.integration_url }}
        NUMBER: ${{ inputs.number }}
        SERVICE: ${{ inputs.service }}
