name: 'OpsLevel - Report Deploy'
author: 'OpsLevel <support@opslevel.com>'
description: 'Create a deploy event for a service in OpsLevel'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  integration_url:
    description: 'The OpsLevel deploy integration url'
    required: true
  service:
    description: 'The service alias for the event'
    required: true
  description:
    description: 'The description or release notes for the event'
    required: true
  environment:
    description: 'The environment for the event'
    required: true
  number:
    description: 'The deploy number for the event - Default: ${GITHUB_RUN_NUMBER}'
    required: true
  deployer_name:
    description: 'The deployer name who created the event - Default: ${GITHUB_ACTOR}'
    required: true
  deployer_email:
    description: 'The deployer email who created the event'
    required: true
  deploy_url:
    description: 'The deployer email who created the event'
    required: true
  deduplication_id:
    description: 'An identifier that can be used to deduplicate deployments'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
