name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Report Deploy with Docker
        uses: ./
        with:
          integration_url: ${{ secrets.DEPLOY_INTEGRATION_URL }}
          service: "report_deploy_github_action"
          use_docker: "true"
      - name: Report Deploy with CLI
        uses: ./
        with:
          integration_url: ${{ secrets.DEPLOY_INTEGRATION_URL }}
          service: "report_deploy_github_action"
          use_docker: "false"
