name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - '**/*'

jobs:
  test-report-deploy-with-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Report Deploy with CLI
        uses: ./
        with:
          integration_url: ${{ secrets.OL_TEST_DEPLOY_URL }}
          service: "report_deploy_github_action"

  test-report-deploy-with-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Report Deploy with Docker
        uses: ./with-docker
        with:
          integration_url: ${{ secrets.OL_TEST_DEPLOY_URL }}
          service: "report_deploy_github_action"
